CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE DADOS_ALUNOS(
ID INT AUTO_INCREMENT,
NOME VARCHAR(30),
IDADE INT,
SERIE VARCHAR(20),
NOTA FLOAT,
PRIMARY KEY (ID)
);

SELECT * FROM DADOS_ALUNOS;
INSERT INTO DADOS_ALUNOS(NOME,IDADE,SERIE,NOTA)
VALUES("DANIEL",11,"6A",6.0),
("CAMILA",14,"8B",8.0),
("MARCOS",15,"1B",10.0),
("LARISSA",17,"3C",7.0);
SELECT * FROM DADOS_ALUNOS WHERE NOTA > 7;
SELECT * FROM DADOS_ALUNOS WHERE NOTA < 7;
UPDATE DADOS_ALUNOS SET NOTA = 8 WHERE ID=1;