CREATE DATABASE DB_GENERATION_GAME_ONLINE;

USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES (
ID BIGINT(5) AUTO_INCREMENT,
 HABILIDADE VARCHAR(255)NOT NULL,
 TIPO VARCHAR(255) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE TB_PERSONAGENS(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
ATAQUE INT NOT NULL,
DEFESA INT NOT NULL,
CARACTERISTICA VARCHAR(255) NOT NULL,
CLASSES_ID BIGINT(5),
PRIMARY KEY(ID),
FOREIGN KEY(CLASSES_ID) REFERENCES TB_CLASSES(ID)
);
SELECT * FROM TB_CLASSES;
SELECT * FROM TB_PERSONAGENS;

INSERT INTO TB_CLASSES(HABILIDADE,TIPO)
VALUES("VELOCIDADE","MÁGICO");
INSERT INTO TB_CLASSES(HABILIDADE,TIPO)
VALUES("FORÇA","HUMANO");

 INSERT INTO TB_PERSONAGENS (NOME,ATAQUE,DEFESA,CARACTERISTICA,CLASSES_ID)
 VALUES("MAGO",2000,1000,"BAIXO",1),
 ("FADA",5000,2000,"ALTO",1),
 ("CAPITAO",4000,3000,"ALTO",2),
 ("REI",1500,1000,"BAIXO",2);
 
 SELECT * FROM TB_PERSONAGENS WHERE  ATAQUE > 2000;
  SELECT * FROM TB_PERSONAGENS WHERE  DEFESA BETWEEN 1000 AND 2000; 

 SELECT * FROM TB_PERSONAGENS WHERE NOME LIKE "C%";
 SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID = TB_CLASSES.ID;
 SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID = TB_CLASSES.ID WHERE TIPO = "MÁGICO";
 



