CREATE DATABASE DB_FARMACIA_GEN;

USE DB_FARMACIA_GEN;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT(5) AUTO_INCREMENT,
TIPO VARCHAR(255) NOT NULL, -- GENERICO OU ORIGINAL --
DESCRICAO VARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
FABRICANTE VARCHAR(255) NOT NULL,
QUANTIDADE_ESTOQUE INT NOT NULL,
PRECO INT NOT NULL,
CATEGORIAS_ID BIGINT(4),
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_CATEGORIAS (TIPO,DESCRICAO)
VALUES ("ORIGINAL","COMPRIMIDO"),
("GENERICO","XAROPE");

INSERT INTO TB_PRODUTOS (NOME,FABRICANTE,QUANTIDADE_ESTOQUE,PRECO,CATEGORIAS_ID)
VALUES("GENPIRONA","NEO GEN",5,10,1),
("CALMANTE58","NEO GEN",3,64,1),
("EXPECTORANTE","NEO GEN",5,54,2),
("ANALGÉSICO","NEO GEN",2,12,1);

SELECT * FROM TB_PRODUTOS WHERE PRECO > 50;
SELECT * FROM TB_PRODUTOS WHERE PRECO BETWEEN 50 AND 60;

SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "C%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID WHERE TIPO = "ORIGINAL";