CREATE DATABASE DB_CIDADE_DAS_CARNES;

USE DB_CIDADE_DAS_CARNES;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT(5) AUTO_INCREMENT,
TIPO VARCHAR(255) NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE TB_PRODUTOS(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
PRECO INT NOT NULL,
QUANTIDADE_ESTOQUE INT NOT NULL,
CATEGORIAS_ID BIGINT(5),
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_CATEGORIAS (TIPO)
VALUES("SUINA"),
("BOVINA");

INSERT INTO TB_PRODUTOS(NOME,PRECO,QUANTIDADE_ESTOQUE,CATEGORIAS_ID)
VALUES("ALCATRA",35,4,2),
("PANCETA",50,5,1),
("PICANHA",150,3,2);

SELECT * FROM TB_PRODUTOS WHERE PRECO > 50;
SELECT * FROM TB_PRODUTOS WHERE PRECO BETWEEN 50 AND 100;

SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "C%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIAS_ID = TB_CATEGORIAS.ID WHERE TIPO = "BOVINA";