CREATE DATABASE RH_GEN;

USE RH_GEN;

CREATE TABLE RH_GEN(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
IDADE INT,
SEXO CHAR(50),
SALARIO INT,
PRIMARY KEY(ID)

);
SELECT * FROM RH_GEN;
INSERT INTO RH_GEN(NOME,IDADE,SEXO,SALARIO)
VALUES ("ISABELLA",20,"FEMININO",3200),
("NAYARA",30,"FEMININO",1500),
("LETICIA",19,"FEMININO",3500);
SELECT * FROM RH_GEN WHERE SALARIO > 2000;
SELECT * FROM RH_GEN WHERE SALARIO < 2000;
UPDATE RH_GEN SET SALARIO = 3000 WHERE ID=2;
